version: '2'
services:
  cognitiodb:
    image: mysql:5.7
    container_name: cognitiodb
    volumes:
      - cognitiodb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - ILICEReverseProxy

  cognitiowp:
    image: wordpress:php7.0
    depends_on:
      - cognitiodb
    container_name: cognitiowp
    restart: always
    expose:
      - '80'
    volumes:
      - cognitiowp_wp_folder:/var/www/html
      - ./.htaccess:/var/www/html/.htaccess
    environment:
     WORDPRESS_DB_HOST: cognitiodb:3306
    env_file:
      - .env
    networks:
     - ILICEReverseProxy

  cognitiomyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - cognitiodb:db
    expose:
      - '80'
    depends_on:
      - cognitiodb
    networks:
      - ILICEReverseProxy

volumes:
   cognitiodb_data:
   cognitiowp_wp_folder:

networks:
  ILICEReverseProxy:
    external: true
