version: '2'
services:
  cognitiodb:
    image: mysql:5.7
    container_name: cognitiodb
    volumes:
      - cognitiodb_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - ILICEReverseProxy

  cognitiowp:
    image: wordpress:php7.0
    depends_on:
      - cognitiodb
    container_name: cognitiowp
    restart: always
    expose:
      - '80'
    ports:
      - '8001:80'
    volumes:
      - cognitiowp_wp_folder:/var/www/html
      - ./.htaccess:/var/www/html/.htaccess
    environment:
     WORDPRESS_DB_HOST: learndb:3306
     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
     - ILICEReverseProxy

  cognitiomyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - cognitiodb:db
    ports:
      - '8001:80'
    expose:
      - '80'
    depends_on:
      - cognitiodb
    networks:
      - ILICEReverseProxy

volumes:
   cognitiodb_data:
   cognitiowp_wp_folder:

networks:
  ILICEReverseProxy:
    external: true
